# Configuration for building documentation on readthedocs.org.

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  #builder: html
  configuration: docs/guide/conf.py

python:
  install:
    - requirements: docs/requirements.txt
